const tintColorLight = '#2f95dc';
const tintColorDark = '#fff';

const colors = {
  light: {
    text: '#000',
    background: '#f8f9fa',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
    borderColor: '#ddd',
    buttonBackground: '#fff',
    activeButtonBackground: '#007bff',
    activeButtonBorder: '#007bff',
    buttonText: '#000',
    activeButtonText: '#fff',
    inputBackground: '#fff',
    inputLabel: '#333',
    success: '#28a745',
    warning: '#ffc107',
    danger: '#dc3545',
    neutral: '#6c757d',
    shadow: '#000',
    badgeText: '#fff',
    detailText: '#495057',
    muscleGroupText: '#6c757d',
    dayCircleBackground: '#007bff',
    dayText: '#fff',
  },
  dark: {
    text: '#fff',
    background: '#343a40',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
    borderColor: '#444',
    buttonBackground: '#000',
    activeButtonBackground: '#fff',
    activeButtonBorder: '#fff',
    buttonText: '#fff',
    activeButtonText: '#000',
    inputBackground: '#000',
    inputLabel: '#fff',
    success: '#28a745',
    warning: '#ffc107',
    danger: '#dc3545',
    neutral: '#6c757d',
    shadow: '#000',
    badgeText: '#fff',
    detailText: '#adb5bd',
    muscleGroupText: '#ced4da',
    dayCircleBackground: '#007bff',
    dayText: '#000',
  },
};

export default colors;
