services:
  react-native-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-native-web
    ports:
      - "8081:8081"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
